const database = {
  firstNames: [
    "sweet",
    "precious",
    "lovely",
    "wonderful",
    "brilliant",
    "brave",
    "amazing",
    "clever",
    "extraordinary",
    "joyful",
    "little",
    "cute",
  ],
  lastNames: [
    "pumpkin",
    "sunshine",
    "sweetheart",
    "cupcake",
    "honey",
    "angel",
    "cutie",
    "treasure",
    "sweetpea",
    "peach",
    "sugar lump",
    "peanut",
    "hellion",
  ],
  phrases: [
    "Great to see you,",
    "Well, hello,",
    "It's my,",
    "Glad to have you here,",
    "Howdy,",
    "My you've grown,",
    "You get bigger every time I see you,",
    "Look it's my favorite grandchild,",
    "Well, isn't it my,",
    "How's my",
  ],
  femaleSoulmates: [
    "Darth Vader",
    "Grigori Rasputin",
    "Elvis Presly",
    "LeGoat James",
    "Hannibal Lecter",
    "the Joker",
    "Freddy Kreuger",
    "Michael Myers",
    "Dracula",
    "Captain America",
    "Draco Malfoy",
    "Patrick Bateman",
    "Count Dracula",
    "President Snow",
    "Count Olaf",
    "Aragorn",
    "Peeta Mellark",
    "Jamie Lannister",
    "Lord Voldemort",
    "Sauron",
  ],
  maleSoulmates: [
    "Mileena",
    "Mother Teresa",
    "Princess Leia",
    "Harley Quinn",
    "Hermione Granger",
    "Katniss Everdeen",
    "Princess Fiona",
    "Princess Peach",
    "Zelda",
    "Taylor Swift",
    "Adele",
    "Cruella di Vil",
    "Dolores Umbridge",
    "Medusa",
    "Bellatrix Lestrange",
  ],

  soulmateLocations: [
    "Walmart cleaning aisle",
    "Trader Joes clearance section",
    "Walgreens ice cream section",
    "weekly bingo table",
    "jazzercise class",
    "pigeon feeding park bench",
    "AARP fan fiction chat room",
    "pharmacy prescription refill line",
    "annual senior living rave",
    "Ace Hardware garden center",
    "community outdoor chess tables",
    "mini-storage auction crowd",
  ],
  situations: [
    "ravaging head lice",
    "explosive diarrhea",
    "manic shoplifting",
    "drunken karaoke skills",
    "pie-eating contest practice",
    "avant garde cat clothes fashion business",
    "bed-wetting",
    "clinically interesting body odor",
    "drunken texts to your boss",
    "collection of eBay toenails",
    "cringey TikTok dances",
    "chronic dad sneezes",
    "relationship with your imaginary friend",
  ],
};

module.exports = { database };
