const database = {
  firstNames: [
    "sweet",
    "precious",
    "lovely",
    "wonderful",
    "brilliant",
    "brave",
    "amazing",
    "clever",
    "extraordinary",
    "joyful",
    "little",
    "cute",
  ],
  lastNames: [
    "pumpkin",
    "sunshine",
    "sweetheart",
    "cupcake",
    "honey",
    "angel",
    "cutie",
    "treasure",
    "sweetpea",
    "peach",
    "sugar lump",
    "peanut",
    "hellion",
  ],
  phrases: [
    "Great to see you,",
    "Well, hello,",
    "It's my,",
    "Glad to have you here,",
    "Howdy,",
    "My you've grown,",
    "You get bigger every time I see you,",
    "Look it's my favorite grandchild,",
    "Well, isn't it my,",
    "How's my",
  ],
  situations: [
    "ravaging head lice",
    "explosive diarrhea",
    "manic shoplifting",
    "drunken karaoke skills",
    "pie-eating contest practice",
    "avant garde cat clothes fashion business",
    "bed-wetting",
    "clinically interesting body odor",
    "drunken texts to your boss",
    "collection of eBay toenails",
    "cringey TikTok dances",
    "chronic dad sneezes",
    "relationship with your imaginary friend",
  ],
};

module.exports = { database };
